name: docs
on:
  push:
    branches:
    - main

jobs:
  tests_and_docs:
    name: Tests and Docs
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

    - name: Install requirements
      run: |
        pip3 install pytest
        pip3 install sphinx-rtd-theme
        pip3 install --upgrade myst-parser
        pip3 install -r requirements.txt
        python3 setup.py install

    - name: Run tests
      run: |
        cd tests
        pytest
    
    - name: Build docs
      run: |
        cd docs
        make html
    
    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/